### ISSUE TITLE
Feature request: pull_array and pull_vector

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/CLIc#323]
I wrote now multiple times this code:

```
int size ...;
std::vector<float> result(size);
gpu_result.read(result);
```

And I'm wondering if it could be put into a `pull_vector` function, which would make my life easier:

```
std::vector<float> result = cle::pull_vector(gpu_result);
```

**Comment by StRigaud** [comment]
The pull_vector would need to be templated. Like I said in your PR, the output vector template type must match the gpu array type.

I did something like that if you look in the `memory.hpp` functions, but I stopped using them because it simply save 1 line of code and this type of function would better fit a user API which CLIc is not.
